// Regenerates js/samples.js from samples/*.txt so the example lab also works when
// index.html is opened directly from disk (file:// cannot fetch the .txt files).
// Usage: node tools/build-samples.js
const fs = require('fs');
const path = require('path');
const dir = path.join(__dirname, '..', 'samples');
const files = fs.readdirSync(dir).filter(f => f.endsWith('.txt')).sort();
const samples = files.map(f => ({ name: f, text: fs.readFileSync(path.join(dir, f), 'utf8') }));
const out = '// Generated by tools/build-samples.js – do not edit by hand.\n' +
  '(function (root) {\n  const CCA = root.CCA = root.CCA || {};\n  CCA.samples = ' + JSON.stringify(samples, null, 2) + ';\n' +
  '  if (typeof module !== \'undefined\' && module.exports) module.exports = CCA;\n})(typeof window !== \'undefined\' ? window : globalThis);\n';
fs.writeFileSync(path.join(__dirname, '..', 'js', 'samples.js'), out);
console.log('Wrote js/samples.js with ' + samples.length + ' sample config(s).');
