/**
 * npm run vfx:pack — turns the generated effect sprites into the particle atlas.
 *
 * Each sprite's black background becomes transparency: colour sprites (fire, sparks, glows) take
 * their brightest channel as alpha and keep their colour; mask sprites (smoke, dust, cracks, splats)
 * become white shapes the game tints. Colours are stored premultiplied (so filtering never makes dark
 * fringes), edges fade out so no square shows, and the sprites go into an 8 × 8 grid of 256 px cells:
 * public/assets/vfx/atlas.webp, with src/render/vfxAtlas.ts naming the cells.
 *
 * Sources: the raw 992 px images in assets-src/vfx/raw/ (gitignored) when present, else the processed
 * 512 px copies in assets-src/vfx/ (committed), which this script also refreshes.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';
import { SPRITES } from './sprites';

const ROOT = new URL('../..', import.meta.url).pathname;
const RAW = join(ROOT, 'assets-src', 'vfx', 'raw');
const KEEP = join(ROOT, 'assets-src', 'vfx');
const CELL = 256;
const COLS = 8;

/** Black point: the generator's "black" isn't quite 0. */
const BLACK = 12 / 255;
/** Cracks come with a grey disc behind the lines: only the bright lines count. */
const EXTRA_BLACK: Record<string, number> = { crack: 0.32 };

const smooth = (e0: number, e1: number, x: number) => {
  const t = Math.min(1, Math.max(0, (x - e0) / (e1 - e0)));
  return t * t * (3 - 2 * t);
};

async function processed(key: string, mask: boolean, size: number): Promise<Buffer> {
  const raw = join(RAW, `${key}.png`);
  const src = existsSync(raw) ? raw : join(KEEP, `${key}.webp`);
  if (existsSync(raw)) {
    // Refresh the committed 512 px copy (straight colour on black, as generated).
    await sharp(raw).resize(512, 512).webp({ quality: 90 }).toFile(join(KEEP, `${key}.webp`));
  }
  const { data } = await sharp(src).resize(size, size).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  const out = Buffer.alloc(size * size * 4);
  const black = BLACK + (EXTRA_BLACK[key.replace(/_\d+$/, '')] ?? 0);
  const level = (v: number) => Math.min(1, Math.max(0, (v / 255 - black) / (1 - black)));
  const edge = 0.07;
  for (let y = 0; y < size; y++) {
    const fy = smooth(0, edge, Math.min(y + 0.5, size - y - 0.5) / size);
    for (let x = 0; x < size; x++) {
      const fall = fy * smooth(0, edge, Math.min(x + 0.5, size - x - 0.5) / size);
      const i = (y * size + x) * 3;
      const r = level(data[i]!);
      const g = level(data[i + 1]!);
      const b = level(data[i + 2]!);
      const a = Math.max(r, g, b) * fall;
      const o = (y * size + x) * 4;
      if (mask) {
        // White shape: premultiplied white is just the alpha.
        out[o] = out[o + 1] = out[o + 2] = out[o + 3] = Math.round(a * 255);
      } else {
        // Colour on black is already premultiplied by its brightest channel.
        out[o] = Math.round(r * fall * 255);
        out[o + 1] = Math.round(g * fall * 255);
        out[o + 2] = Math.round(b * fall * 255);
        out[o + 3] = Math.round(a * 255);
      }
    }
  }
  return out;
}

async function main(): Promise<void> {
  mkdirSync(KEEP, { recursive: true });
  if (SPRITES.length > COLS * COLS) throw new Error(`${SPRITES.length} sprites don't fit an ${COLS} × ${COLS} atlas`);
  const size = CELL * COLS;
  const comps: { input: Buffer; left: number; top: number }[] = [];
  for (const [i, s] of SPRITES.entries()) {
    const buf = await processed(s.key, !!s.mask, CELL);
    comps.push({ input: buf, left: (i % COLS) * CELL, top: Math.floor(i / COLS) * CELL });
  }
  const outDir = join(ROOT, 'public', 'assets', 'vfx');
  mkdirSync(outDir, { recursive: true });
  // Premultiplied colours: compose without sharp's own premultiplication.
  const atlas = Buffer.alloc(size * size * 4);
  for (const c of comps) {
    const src = c.input;
    for (let y = 0; y < CELL; y++) src.copy(atlas, ((c.top + y) * size + c.left) * 4, y * CELL * 4, (y + 1) * CELL * 4);
  }
  await sharp(atlas, { raw: { width: size, height: size, channels: 4 } }).webp({ quality: 90, alphaQuality: 95, exact: true }).toFile(join(outDir, 'atlas.webp'));
  const frames = SPRITES.map((s, i) => `  ${s.key}: ${i},`).join('\n');
  writeFileSync(
    join(ROOT, 'src', 'render', 'vfxAtlas.ts'),
    `// Generated by scripts/vfx/pack.ts — the cells of public/assets/vfx/atlas.webp.\n` +
      `/** Cells per row (and rows) in the atlas. */\nexport const ATLAS_COLS = ${COLS};\n\n` +
      `/** Additive sprites keep their colour; mask sprites are white shapes the game tints. */\n` +
      `export const MASK_SPRITES = new Set<string>(${JSON.stringify(SPRITES.filter((s) => s.mask).map((s) => s.key))});\n\n` +
      `export const SPRITE = {\n${frames}\n} as const;\n\nexport type SpriteKey = keyof typeof SPRITE;\n`,
  );
  console.log(`Packed ${SPRITES.length} sprites into public/assets/vfx/atlas.webp (${size} × ${size}).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
