/** Core component definitions. Components are plain data — no methods, no Three.js objects. */
import type { Bonus, ClassDef, DamageType, StatusId } from '../data/schemas';
import type { Item, Slot } from '../data/loot/schemas';
import { defineComponent, type Entity } from './ecs';

/** World-space position (metres, y up) and facing (radians around y, 0 = +z). */
export interface Transform {
  x: number;
  y: number;
  z: number;
  facing: number;
  /** Previous tick's values, used by the renderer to interpolate. */
  prevX: number;
  prevY: number;
  prevZ: number;
  prevFacing: number;
}
export const Transform = defineComponent<Transform>('Transform');

export function makeTransform(x = 0, y = 0, z = 0, facing = 0): Transform {
  return { x, y, z, facing, prevX: x, prevY: y, prevZ: z, prevFacing: facing };
}

/** Can move on the ground plane. `vx/vz` is the desired velocity this tick (m/s). */
export interface Mover {
  speed: number;
  /** Multiplier from statuses (0 = stunned, <1 = chilled). Recomputed every tick. */
  speedMul: number;
  /** How fast the entity turns to face its movement (radians/s). */
  turnRate: number;
  vx: number;
  vz: number;
}
export const Mover = defineComponent<Mover>('Mover');

/** Tag: driven by player input. */
export type PlayerControlled = Record<string, never>;
export const PlayerControlled = defineComponent<PlayerControlled>('PlayerControlled');

/** Walk toward a ground point (click-to-move). Removed on arrival. */
export interface MoveTarget {
  x: number;
  z: number;
}
export const MoveTarget = defineComponent<MoveTarget>('MoveTarget');

/** Drawn by the render layer using the asset (or its placeholder) from the manifest. */
export interface Renderable {
  assetId: string;
  /** Uniform scale applied to the model (default 1). */
  scale?: number;
}
export const Renderable = defineComponent<Renderable>('Renderable');

// ---- Combat -------------------------------------------------------------------

export type Team = 'player' | 'enemy';
export interface Faction {
  team: Team;
}
export const Faction = defineComponent<Faction>('Faction');

export interface Health {
  current: number;
  max: number;
}
export const Health = defineComponent<Health>('Health');

/** Offensive and defensive numbers used by the damage formula (docs/damage-formula.md). */
export interface CombatStats {
  level: number;
  weaponDamage: number;
  mainStat: number;
  critChance: number;
  /** Bonus on top of 1× for crits: 0.5 → crits deal 1.5×. */
  critDamage: number;
  armor: number;
  resist: Partial<Record<DamageType, number>>;
  /** Additive "+x% damage" bonuses — summed into one bucket. */
  additive: Bonus[];
  /** Multiplicative "×x% damage" bonuses — each multiplies separately. */
  multiplicative: Bonus[];
  /** Tags used by conditional bonuses ("elite"). */
  tags: string[];
  /** Fractions (0.1 = 10 %). Speeds up skill wind-up and recovery. */
  attackSpeed: number;
  /** Fraction removed from skill cooldowns (capped at 50 %). */
  cooldownReduction: number;
  /** Bonus to resource generated by skills. */
  resourceGen: number;
  /** Bonus to barriers received. */
  barrierBonus: number;
  /** Bonus to potion healing. */
  potionHealing: number;
  /** Multiplicative reduction of all damage taken (capped at 50 %). */
  damageReduction: number;
  /** Life restored whenever an enemy dies. */
  lifeOnKill: number;
}

/** Sensible zero values for the optional CombatStats fields (enemies, tests). */
export const NO_EXTRA_STATS = {
  attackSpeed: 0,
  cooldownReduction: 0,
  resourceGen: 0,
  barrierBonus: 0,
  potionHealing: 0,
  damageReduction: 0,
  lifeOnKill: 0,
} as const;
export const CombatStats = defineComponent<CombatStats>('CombatStats');

/** Circle collider. Air colliders only push other air colliders (drones float over crowds). */
export interface Collider {
  radius: number;
  mass: number;
  layer: 'ground' | 'air';
  /** Static obstacles never move. */
  isStatic: boolean;
}
export const Collider = defineComponent<Collider>('Collider');

export interface StatusInstance {
  id: StatusId;
  remaining: number;
  duration: number;
  /** DoT damage per second (pre-mitigation). */
  dps: number;
  /** Barrier points left. */
  amount: number;
  /** Damage accumulated since the last DoT tick. */
  pending: number;
  sourceTeam: Team;
  attackerLevel: number;
}
export interface StatusEffects {
  list: StatusInstance[];
  /** False while stunned/frozen. Recomputed every tick by the status system. */
  canAct: boolean;
  /** Time until the next DoT damage tick. */
  dotTimer: number;
}
export const StatusEffects = defineComponent<StatusEffects>('StatusEffects');

/** Class resource (Heat for Bastion). */
export interface Resource {
  kind: 'heat' | 'focus' | 'biomass';
  current: number;
  max: number;
  /** Seconds since the owner last dealt or took damage. */
  sinceCombat: number;
  /** Seconds spent at max (Heat overheat). */
  atMaxFor: number;
  overheatTick: number;
  config: ClassDef['resource'];
}
export const Resource = defineComponent<Resource>('Resource');

export interface CastState {
  skillId: string;
  elapsed: number;
  fired: boolean;
  aimX: number;
  aimZ: number;
}
export interface SkillRequest {
  slot: number;
  aimX: number;
  aimZ: number;
  /** Seconds the request stays buffered while the caster is busy. */
  ttl: number;
}
export interface SkillUser {
  classId: string;
  slots: (string | null)[];
  cooldowns: Record<string, number>;
  cast: CastState | null;
  request: SkillRequest | null;
  dodgeCooldown: number;
  dodgeRequested: { x: number; z: number } | null;
  potionCharges: number;
  potionRecharge: number;
  potionRequested: boolean;
}
export const SkillUser = defineComponent<SkillUser>('SkillUser');

/** Scripted movement that overrides normal movement (leaps, dodges). */
export interface ForcedMove {
  fromX: number;
  fromZ: number;
  toX: number;
  toZ: number;
  elapsed: number;
  duration: number;
  height: number;
  /** Skill whose landing effect fires on arrival, if any. */
  landingSkill: string | null;
}
export const ForcedMove = defineComponent<ForcedMove>('ForcedMove');

/** Ignores damage (dodge i-frames). */
export interface Invulnerable {
  remaining: number;
}
export const Invulnerable = defineComponent<Invulnerable>('Invulnerable');

export interface Knockback {
  vx: number;
  vz: number;
  remaining: number;
}
export const Knockback = defineComponent<Knockback>('Knockback');

export type AiState = 'idle' | 'chase' | 'windup' | 'recover';
export interface EnemyAI {
  defId: string;
  state: AiState;
  timer: number;
  cooldown: number;
  aggro: boolean;
  aimX: number;
  aimZ: number;
  strafeDir: 1 | -1;
  strafeTimer: number;
  wanderX: number;
  wanderZ: number;
  /** Increments every time an attack wind-up starts (lets visuals restart the attack clip). */
  attackSeq: number;
}
export const EnemyAI = defineComponent<EnemyAI>('EnemyAI');

export interface Projectile {
  team: Team;
  vx: number;
  vz: number;
  radius: number;
  remaining: number;
  damage: number;
  damageType: DamageType;
  attackerLevel: number;
  owner: Entity;
}
export const Projectile = defineComponent<Projectile>('Projectile');

/** Ground area that repeatedly applies statuses to the opposing team (spore clouds). */
export interface Hazard {
  team: Team;
  radius: number;
  remaining: number;
  duration: number;
  tickTimer: number;
  applies: { status: StatusId; duration: number; dps?: number }[];
  attackerLevel: number;
}
export const Hazard = defineComponent<Hazard>('Hazard');

export interface Dead {
  elapsed: number;
  /** Seconds before the corpse is removed (players are never removed). */
  removeAfter: number;
  /** Direction the body falls (radians). */
  fallDir: number;
}
export const Dead = defineComponent<Dead>('Dead');

/** Marks which wave spawned an enemy. */
export interface WaveMember {
  wave: number;
}
export const WaveMember = defineComponent<WaveMember>('WaveMember');

/** Click-to-move attack order: walk into range of this enemy, then use the basic skill. */
export interface AttackTarget {
  target: Entity;
}
export const AttackTarget = defineComponent<AttackTarget>('AttackTarget');

/** Singleton tracking the wave encounter in the test arena. */
export interface EncounterState {
  encounterId: string;
  /** Number of waves started so far (1-based once the first wave spawns). */
  wave: number;
  phase: 'intermission' | 'active';
  timer: number;
  alive: number;
}
export const EncounterState = defineComponent<EncounterState>('EncounterState');

// ---- Progression & loot -------------------------------------------------------

export interface Attributes {
  strength: number;
  dexterity: number;
  intelligence: number;
  willpower: number;
}

export interface Progression {
  level: number;
  xp: number;
  skillPoints: number;
}
export const Progression = defineComponent<Progression>('Progression');

export interface Inventory {
  /** Backpack grid (Diablo 4 style: every item takes one cell). */
  grid: (Item | null)[];
  equipped: Partial<Record<Slot, Item>>;
  gold: number;
}
export const Inventory = defineComponent<Inventory>('Inventory');

/** Derived numbers shown in the character panel (filled by the stats system). */
export interface DerivedStats {
  attributes: Attributes;
  moveSpeedBonus: number;
  /** Rough damage-per-hit estimate for comparisons. */
  damageEstimate: number;
}
export const DerivedStats = defineComponent<DerivedStats>('DerivedStats');

/** Enemy level (scales life, damage, XP and loot). */
export interface Level {
  value: number;
}
export const Level = defineComponent<Level>('Level');

export interface GroundItem {
  item: Item;
  /** Seconds since it dropped (for the pop-out animation). */
  age: number;
}
export const GroundItem = defineComponent<GroundItem>('GroundItem');

export interface GroundGold {
  amount: number;
  age: number;
}
export const GroundGold = defineComponent<GroundGold>('GroundGold');

/** Walk to this ground item and pick it up on arrival. */
export interface PickupTarget {
  target: Entity;
}
export const PickupTarget = defineComponent<PickupTarget>('PickupTarget');
