/** Core component definitions. Components are plain data — no methods, no Three.js objects. */
import type { Bonus, ClassDef, DamageType, Impact, StatusId } from '../data/schemas';
import type { Item, Slot } from '../data/loot/schemas';
import type { CompiledSkill } from '../systems/skillCompile';
import type { TreeState } from '../systems/skillTree';
import { defineComponent, type Entity } from './ecs';

/** World-space position (metres, y up) and facing (radians around y, 0 = +z). */
export interface Transform {
  x: number;
  y: number;
  z: number;
  facing: number;
  /** Previous tick's values, used by the renderer to interpolate. */
  prevX: number;
  prevY: number;
  prevZ: number;
  prevFacing: number;
}
export const Transform = defineComponent<Transform>('Transform');

export function makeTransform(x = 0, y = 0, z = 0, facing = 0): Transform {
  return { x, y, z, facing, prevX: x, prevY: y, prevZ: z, prevFacing: facing };
}

/** Can move on the ground plane. `vx/vz` is the desired velocity this tick (m/s). */
export interface Mover {
  speed: number;
  /** Multiplier from statuses (0 = stunned, <1 = chilled). Recomputed every tick. */
  speedMul: number;
  /** How fast the entity turns to face its movement (radians/s). */
  turnRate: number;
  vx: number;
  vz: number;
}
export const Mover = defineComponent<Mover>('Mover');

/** Tag: driven by player input. */
export type PlayerControlled = Record<string, never>;
export const PlayerControlled = defineComponent<PlayerControlled>('PlayerControlled');

/** Walk toward a ground point (click-to-move). Removed on arrival. */
export interface MoveTarget {
  x: number;
  z: number;
}
export const MoveTarget = defineComponent<MoveTarget>('MoveTarget');

/** Drawn by the render layer using the asset (or its placeholder) from the manifest. */
export interface Renderable {
  assetId: string;
  /** Uniform scale applied to the model (default 1). */
  scale?: number;
  /** Draw as a translucent hologram (decoys). */
  hologram?: boolean;
  /** Constant emissive glow (raised minions glow Lumen green). */
  glow?: string;
  /** Huge landmark: never distance-culled and ignores fog. */
  landmark?: boolean;
}
export const Renderable = defineComponent<Renderable>('Renderable');

// ---- Combat -------------------------------------------------------------------

export type Team = 'player' | 'enemy';
export interface Faction {
  team: Team;
}
export const Faction = defineComponent<Faction>('Faction');

export interface Health {
  current: number;
  max: number;
}
export const Health = defineComponent<Health>('Health');

/** Offensive and defensive numbers used by the damage formula (docs/damage-formula.md). */
export interface CombatStats {
  level: number;
  weaponDamage: number;
  mainStat: number;
  critChance: number;
  /** Bonus on top of 1× for crits: 0.5 → crits deal 1.5×. */
  critDamage: number;
  armor: number;
  resist: Partial<Record<DamageType, number>>;
  /** Additive "+x% damage" bonuses — summed into one bucket. */
  additive: Bonus[];
  /** Multiplicative "×x% damage" bonuses — each multiplies separately. */
  multiplicative: Bonus[];
  /** Tags used by conditional bonuses ("elite"). */
  tags: string[];
  /** Fractions (0.1 = 10 %). Speeds up skill wind-up and recovery. */
  attackSpeed: number;
  /** Fraction removed from skill cooldowns (capped at 50 %). */
  cooldownReduction: number;
  /** Bonus to resource generated by skills. */
  resourceGen: number;
  /** Bonus to barriers received. */
  barrierBonus: number;
  /** Bonus to potion healing. */
  potionHealing: number;
  /** Multiplicative reduction of all damage taken (capped at 50 %). */
  damageReduction: number;
  /** Life restored whenever an enemy dies. */
  lifeOnKill: number;
}

/** Sensible zero values for the optional CombatStats fields (enemies, tests). */
export const NO_EXTRA_STATS = {
  attackSpeed: 0,
  cooldownReduction: 0,
  resourceGen: 0,
  barrierBonus: 0,
  potionHealing: 0,
  damageReduction: 0,
  lifeOnKill: 0,
} as const;
export const CombatStats = defineComponent<CombatStats>('CombatStats');

/** Circle collider. Air colliders only push other air colliders (drones float over crowds). */
export interface Collider {
  radius: number;
  mass: number;
  layer: 'ground' | 'air';
  /** Static obstacles never move. */
  isStatic: boolean;
}
export const Collider = defineComponent<Collider>('Collider');

export interface StatusInstance {
  id: StatusId;
  remaining: number;
  duration: number;
  /** DoT damage per second (pre-mitigation). */
  dps: number;
  /** Barrier points left. */
  amount: number;
  /** Damage accumulated since the last DoT tick. */
  pending: number;
  sourceTeam: Team;
  attackerLevel: number;
}
export interface StatusEffects {
  list: StatusInstance[];
  /** False while stunned/frozen. Recomputed every tick by the status system. */
  canAct: boolean;
  /** Time until the next DoT damage tick. */
  dotTimer: number;
}
export const StatusEffects = defineComponent<StatusEffects>('StatusEffects');

/** Class resource (Heat for Bastion). */
export interface Resource {
  kind: 'heat' | 'focus' | 'biomass';
  current: number;
  max: number;
  /** Seconds since the owner last dealt or took damage. */
  sinceCombat: number;
  /** Seconds spent at max (Heat overheat). */
  atMaxFor: number;
  overheatTick: number;
  config: ClassDef['resource'];
}
export const Resource = defineComponent<Resource>('Resource');

export interface CastState {
  skillId: string;
  elapsed: number;
  fired: boolean;
  aimX: number;
  aimZ: number;
}
export interface SkillRequest {
  slot: number;
  aimX: number;
  aimZ: number;
  /** Seconds the request stays buffered while the caster is busy. */
  ttl: number;
}
export interface SkillUser {
  classId: string;
  slots: (string | null)[];
  /** Skill tree allocation. */
  tree: TreeState;
  /** Effective skills after ranks, tree modifiers, aspects and uniques (rebuilt by the stats system). */
  compiled: Record<string, CompiledSkill>;
  cooldowns: Record<string, number>;
  cast: CastState | null;
  request: SkillRequest | null;
  dodgeCooldown: number;
  dodgeRequested: { x: number; z: number } | null;
  potionCharges: number;
  potionRecharge: number;
  potionRequested: boolean;
}
export const SkillUser = defineComponent<SkillUser>('SkillUser');

/** Scripted movement that overrides normal movement (leaps, dodges). */
export interface ForcedMove {
  fromX: number;
  fromZ: number;
  toX: number;
  toZ: number;
  elapsed: number;
  duration: number;
  height: number;
  /** Skill whose landing effect fires on arrival, if any. */
  landingSkill: string | null;
}
export const ForcedMove = defineComponent<ForcedMove>('ForcedMove');

/** Ignores damage (dodge i-frames). */
export interface Invulnerable {
  remaining: number;
}
export const Invulnerable = defineComponent<Invulnerable>('Invulnerable');

export interface Knockback {
  vx: number;
  vz: number;
  remaining: number;
}
export const Knockback = defineComponent<Knockback>('Knockback');

export type AiState = 'idle' | 'chase' | 'windup' | 'recover';
export interface EnemyAI {
  defId: string;
  state: AiState;
  timer: number;
  cooldown: number;
  aggro: boolean;
  aimX: number;
  aimZ: number;
  strafeDir: 1 | -1;
  strafeTimer: number;
  wanderX: number;
  wanderZ: number;
  /** Increments every time an attack wind-up starts (lets visuals restart the attack clip). */
  attackSeq: number;
  /** Shots fired so far in the current burst (machine guns). */
  burstFired?: number;
  /** Open-world pack this enemy belongs to (pack spawner). */
  pack?: string;
  /** Attack tempo multiplier (boss phases): >1 = faster wind-ups and cooldowns. */
  tempo?: number;
  /** Flamethrower stream: seconds left and time to the next tick. */
  channel?: number;
  channelTick?: number;
  /** Front shield: seconds it stays up, and until it can rise again. */
  shieldUp?: number;
  shieldCooldown?: number;
  /** Seconds to the next patch of burning ground (trail). */
  trailTimer?: number;
  /** Melee swings so far (grab every Nth). */
  swings?: number;
  /** Revives left and the time until the next one. */
  revives?: number;
  reviveCooldown?: number;
  /** The corpse being revived during the wind-up. */
  reviveTarget?: Entity;
  // ---- Region 3 behaviours ----
  /** Melee hits that landed (root every Nth). */
  landed?: number;
  /** Vine lash: cooldown, and the wind-up left while a pull is being telegraphed. */
  pullCooldown?: number;
  pullTimer?: number;
  /** Seconds to the next heal pulse (Mossborn). */
  healTimer?: number;
  /** Seconds spent fighting, and until the next call for help (Cocoon Warden). */
  fightTime?: number;
  reinforceTimer?: number;
  /** Seconds to the next lobbed spore cloud, and the clouds still in the air. */
  cloudTimer?: number;
  clouds?: { x: number; z: number; t: number }[];
  // ---- Deep Mines ----
  /** Blind Hound: a noise it is running toward. */
  investigate?: { x: number; z: number };
  shieldAllyTimer?: number;
  /** Burrower: underground until it surfaces at the warned spot. */
  burrowed?: boolean;
  burrowTimer?: number;
  surfaceAt?: { x: number; z: number; t: number } | null;
  /** Crystal Sentinel: shell left (absorbs damage until broken). */
  shell?: number;
  /** Infected Miner: seconds to the next stick of dynamite, and the ones lit. */
  dynamiteTimer?: number;
  bombs?: { x: number; z: number; t: number }[];
  teleportTimer?: number;
  /** Shield Officer: dome up until (ctx.time), and the next one. */
  domeUntil?: number;
  domeTimer?: number;
  /** Lumen Giant: its fungi, and when it rises again after falling while they stand. */
  fungi?: Entity[];
  regrowAt?: number;
}
export const EnemyAI = defineComponent<EnemyAI>('EnemyAI');

export interface Projectile {
  team: Team;
  vx: number;
  vz: number;
  radius: number;
  remaining: number;
  /** Enemy bolts: damage fixed at fire time. Ignored when `skill` is set. */
  damage: number;
  damageType: DamageType;
  attackerLevel: number;
  owner: Entity;
  /** Player skill projectiles: the hit is computed on impact with the owner's stats. */
  skill?: {
    skillId: string;
    impact: Impact;
    /** Enemies it can still pass through. */
    pierce: number;
    explodeRadius: number;
    /** Resource for the owner on the first hit of this cast. */
    gain: number;
    hit: Entity[];
    color: string;
  };
}
export const Projectile = defineComponent<Projectile>('Projectile');

/** Ground area that repeatedly applies statuses to the opposing team (spore clouds). */
export interface Hazard {
  team: Team;
  radius: number;
  /** Ground colour (default: toxic green). */
  color?: string;
  remaining: number;
  duration: number;
  tickTimer: number;
  applies: { status: StatusId; duration: number; dps?: number }[];
  attackerLevel: number;
  /** A ring: only the band between `inner` and `radius` hurts (a collapsing arena floor). */
  inner?: number;
}
export const Hazard = defineComponent<Hazard>('Hazard');

export interface Dead {
  elapsed: number;
  /** Seconds before the corpse is removed (players are never removed). */
  removeAfter: number;
  /** Direction the body falls (radians). */
  fallDir: number;
  /** A corpse that Xenomant skills can still use. */
  corpse?: boolean;
}
export const Dead = defineComponent<Dead>('Dead');

/** Marks which wave spawned an enemy. */
export interface WaveMember {
  wave: number;
}
export const WaveMember = defineComponent<WaveMember>('WaveMember');

/** Click-to-move attack order: walk into range of this enemy, then use the basic skill. */
export interface AttackTarget {
  target: Entity;
}
export const AttackTarget = defineComponent<AttackTarget>('AttackTarget');

/** Singleton tracking the wave encounter in the test arena. */
export interface EncounterState {
  encounterId: string;
  /** Number of waves started so far (1-based once the first wave spawns). */
  wave: number;
  phase: 'intermission' | 'active';
  timer: number;
  alive: number;
}
export const EncounterState = defineComponent<EncounterState>('EncounterState');

// ---- Progression & loot -------------------------------------------------------

export interface Attributes {
  strength: number;
  dexterity: number;
  intelligence: number;
  willpower: number;
}

export interface Progression {
  level: number;
  xp: number;
  skillPoints: number;
  /** Skill points already granted by Region Restoration (account-wide rewards). */
  restorationGranted?: number;
}
export const Progression = defineComponent<Progression>('Progression');

export interface Inventory {
  /** Backpack grid (Diablo 4 style: every item takes one cell). */
  grid: (Item | null)[];
  equipped: Partial<Record<Slot, Item>>;
  gold: number;
  /** Aspects extracted at the Technician, ready to imprint. */
  aspects?: { id: string; value: number }[];
}
export const Inventory = defineComponent<Inventory>('Inventory');

/** Derived numbers shown in the character panel (filled by the stats system). */
export interface DerivedStats {
  attributes: Attributes;
  moveSpeedBonus: number;
  /** Rough damage-per-hit estimate for comparisons. */
  damageEstimate: number;
}
export const DerivedStats = defineComponent<DerivedStats>('DerivedStats');

/** Enemy level (scales life, damage, XP and loot). */
export interface Level {
  value: number;
}
export const Level = defineComponent<Level>('Level');

export interface GroundItem {
  item: Item;
  /** Seconds since it dropped (for the pop-out animation). */
  age: number;
}
export const GroundItem = defineComponent<GroundItem>('GroundItem');

export interface GroundGold {
  amount: number;
  age: number;
}
export const GroundGold = defineComponent<GroundGold>('GroundGold');

/** Walk to this ground item and pick it up on arrival. */
export interface PickupTarget {
  target: Entity;
}
export const PickupTarget = defineComponent<PickupTarget>('PickupTarget');

/** Walking to a clicked object (NPC, crate, teleporter…) to use it on arrival. */
export interface InteractTarget {
  target: Entity;
}
export const InteractTarget = defineComponent<InteractTarget>('InteractTarget');

/** An impact that lands after a delay: orbital strikes, grenades, bomblets. */
export interface DelayedStrike {
  caster: Entity;
  skillId: string;
  remaining: number;
  radius: number;
  /** Total delay, for arc visuals. */
  duration: number;
  /** Override the skill's own impact (bomblets); default: the skill effect. */
  impact?: Impact;
  vfx: 'orbital' | 'grenade' | 'bomblet';
  /** Where the throw started (grenade arcs). */
  fromX: number;
  fromZ: number;
}
export const DelayedStrike = defineComponent<DelayedStrike>('DelayedStrike');

/** A mine: arms, then explodes when an opposing entity comes within `triggerRadius`. */
export interface Trap {
  owner: Entity;
  skillId: string;
  team: Team;
  arming: number;
  remaining: number;
  triggerRadius: number;
  radius: number;
}
export const Trap = defineComponent<Trap>('Trap');

/** Something the player created that expires (decoys, later minions and summons). */
export interface Summon {
  owner: Entity;
  remaining: number;
  /** Skill that created it (for its burst on expiry). */
  skillId: string;
  kind: 'decoy' | 'minion' | 'summon';
}
export const Summon = defineComponent<Summon>('Summon');

/** Enemies within `radius` attack this entity instead of the player. */
export interface Taunt {
  radius: number;
}
export const Taunt = defineComponent<Taunt>('Taunt');

/** A raised corpse fighting for its owner. */
export interface MinionAI {
  owner: Entity;
  state: 'follow' | 'windup' | 'recover';
  timer: number;
  cooldown: number;
  attackCooldown: number;
  attackRange: number;
  windup: number;
  coefficient: number;
  damageType: DamageType;
  ranged: boolean;
  applies: { status: StatusId; duration: number; coefficient?: number }[];
  target: Entity | null;
  /** Increments per attack (restarts the attack clip). */
  attackSeq: number;
  /** Tick it was raised (oldest minions are replaced first). */
  born: number;
}
export const MinionAI = defineComponent<MinionAI>('MinionAI');

/** A draining link from the owner to a target (Parasite Link). */
export interface Tether {
  owner: Entity;
  target: Entity;
  skillId: string;
  remaining: number;
  tickTimer: number;
  interval: number;
  maxRange: number;
}
export const Tether = defineComponent<Tether>('Tether');

/** A stationary summon that slams around itself on an interval (Wrath of Lumen). */
export interface Turret {
  owner: Entity;
  skillId: string;
  interval: number;
  timer: number;
  slamSeq: number;
}
export const Turret = defineComponent<Turret>('Turret');

// ---- Open world -------------------------------------------------------------------

/** A point of interest the player can use with the interact key (docs/world-and-gameplay.md §3). */
export interface Interactable {
  /** Point-of-interest id (or teleporter id). */
  poi: string;
  kind: import('../data/zones/zoneTypes').PoiKind | 'teleporter' | 'questObject' | 'stash' | 'portal' | 'generator' | 'instanceKey' | 'cache' | 'eventObject' | 'valve' | 'cage' | 'compressor' | 'lever' | 'mirror';
  /** Use radius (m). */
  radius: number;
  /** Spent for good (opened, read, claimed). */
  used: boolean;
  /** Reusable objects (pylons, supply crates) come back at this time (ctx.time). */
  readyAt: number;
}
export const Interactable = defineComponent<Interactable>('Interactable');

/** Breakable object: explosive barrels go off when hit, chaining into each other. */
export interface Destructible {
  /** Hit radius (m). */
  radius: number;
  /** Blast when destroyed (barrels); null = just breaks. */
  blast: { radius: number; flat: number } | null;
  /** Glowing crystal (Hydroponic Vaults): blinds enemies in `radius` for `duration` s, grows back after `regrow` s. */
  blind?: { radius: number; duration: number; regrow: number };
}
export const Destructible = defineComponent<Destructible>('Destructible');

/** A pending explosion: barrels caught in a blast, Chain Reaction corpses, exploding elites. */
export interface Blast {
  fuse: number;
  radius: number;
  /** Player whose weapon damage scales the blast (Chain Reaction); null = environmental. */
  owner: Entity | null;
  coefficient: number;
  /** Environmental damage to enemies (before mitigation). */
  flat: number;
  hurtsEnemies: boolean;
  /** Damage to players caught in it: a fraction of their max life and/or a flat amount. */
  player: { fraction: number; damage: number; level: number } | null;
}
export const Blast = defineComponent<Blast>('Blast');

/** Account-wide permanent bonuses on the player (Echo Relics, Restoration). */
export interface AccountBonuses {
  effects: import('../data/effects').Effect[];
  /** Region Restoration rewards. */
  potionCharges?: number;
  goldFind?: number;
}
export const AccountBonuses = defineComponent<AccountBonuses>('AccountBonuses');

/** Spawned for a quest step (named targets, objects, the escorted tanker, quest-only NPCs). */
export interface QuestTag {
  quest: string;
  step: number;
}
export const QuestTag = defineComponent<QuestTag>('QuestTag');

/** Shown instead of the enemy type's name (named quest targets, rare elites). */
export interface DisplayName {
  /** Language key, or a literal name when `literal` is set. */
  key: string;
  literal?: boolean;
}
export const DisplayName = defineComponent<DisplayName>('DisplayName');

/** A vehicle the player escorts along a path (it waits when the player falls behind). */
export interface Escort {
  path: [number, number][];
  next: number;
  leash: number;
}
export const Escort = defineComponent<Escort>('Escort');

/** A hub NPC (talked to with the interact key). */
export interface Npc {
  id: string;
}
export const Npc = defineComponent<Npc>('Npc');

/** Champion or rare elite: its affixes and their timers. */
export interface Elite {
  kind: 'champion' | 'rare' | 'named';
  affixes: import('../data/elites').EliteAffix[];
  /** Seconds until each timed affix fires again. */
  timers: Partial<Record<import('../data/elites').EliteAffix, number>>;
  shieldUsed: boolean;
  mirrored: boolean;
  /** Mirror copies drop nothing. */
  copy: boolean;
}
export const Elite = defineComponent<Elite>('Elite');

/** A hazard that appears after a warning (snaring fields). */
export interface PendingHazard {
  fuse: number;
  hazard: Hazard;
}
export const PendingHazard = defineComponent<PendingHazard>('PendingHazard');

/** Non-enemy things the player can click to attack (spore nests, Spore Feeders). */
export interface Targetable {
  /** Spawns adds every `every` seconds while the player is near (nests). */
  spawn?: { enemy: string; count: number; every: number; timer: number };
}
export const Targetable = defineComponent<Targetable>('Targetable');

/** A boss: its phase script, timers and the adds it summoned. */
export interface Boss {
  script: string | null;
  phase: number;
  timers: { adds: number; plates: number; spores: number; fireballs?: number; shrink?: number; tentacles?: number; beams?: number; sweep?: number; sweepTick?: number; teleport?: number };
  engaged: boolean;
  /** Arena centre and radius (spore fields, resets). */
  arena: { x: number; z: number; radius: number };
  adds: Entity[];
  /** Cover plates thrown in phase 2, and other arena changes (the collapsing floor); removed on reset. */
  plates: Entity[];
  /** Warned impacts: plates (leave cover), fireballs (don't), the next floor collapse, or a spore beam along `facing`. */
  pending: { x: number; z: number; t: number; kind?: 'plate' | 'fireball' | 'shrink' | 'beam' | 'pulse'; facing?: number }[];
  baseSpeed: number;
  /** Collapse steps taken (shrinking arena). */
  shrinkStep?: number;
  /** Renderable look before a transformation. */
  baseLook?: { scale: number; glow?: string | undefined };
  // ---- The Warden of the Mother Tree ----
  /** Damage taken multiplier (armour plates still on: less; rooted: none). */
  damageTaken?: number;
  /** Armour plates (separate targets that ride on the boss). */
  parts?: Entity[];
  /** Root Nodes that hold a rooted boss, and the vines that cover the floor meanwhile. */
  nodes?: Entity[];
  vines?: Entity[];
}
export const Boss = defineComponent<Boss>('Boss');

/** Riding the motorbike. */
export interface Mounted {
  speedMul: number;
  /** Life last tick (a big drop throws you off). */
  lastLife: number;
}
export const Mounted = defineComponent<Mounted>('Mounted');
