// Går igenom de nya funktionerna i version 2 och letar efter fel.
const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  const ctx = await b.newContext({ viewport: { width: 1280, height: 760 } });
  const p = await ctx.newPage();
  const errs = [];
  p.on('pageerror', e => errs.push('pageerror: ' + e.message + ' | ' + (e.stack || '').split('\n').slice(1, 3).join(' | ')));
  p.on('console', m => { if (m.type() === 'error') errs.push('console: ' + m.text()); });
  p.setDefaultTimeout(30000);
  const out = (process.env.OUT || require('os').tmpdir()) + '/';
  const step = s => console.log('• ' + s);
  await p.addInitScript(() => { try { const s = JSON.parse(localStorage.getItem('krabba-passet.settings') || '{}'); s.lastVersion = '6.0'; localStorage.setItem('krabba-passet.settings', JSON.stringify(s)); } catch (e) {} });
  await p.goto('http://localhost:8765/index.html', { waitUntil: 'domcontentloaded' });
  await p.waitForTimeout(4000);
  await p.waitForTimeout(2000);
  await p.evaluate(() => { NV.game.world.lock = () => {}; });
  await p.click('[data-week="1"]'); await p.waitForTimeout(300); await p.click('#dialog button.primary');
  step('rackvy');
  await p.evaluate(() => NV.game.onInteract({ type: 'rack', id: 'A' })); await p.waitForTimeout(600);
  await p.screenshot({ path: out + 'n_rack.png' });
  await p.keyboard.press('Escape');
  step('karta');
  await p.evaluate(() => NV.game.ui.mapDialog()); await p.waitForTimeout(600);
  await p.screenshot({ path: out + 'n_map.png' });
  await p.click('[data-zone="0"]'); await p.waitForTimeout(1200);
  console.log('   plats efter snabbresa:', await p.evaluate(() => NV.game.world.zone().name));
  step('inställningar');
  await p.evaluate(() => NV.game.ui.settingsDialog()); await p.waitForTimeout(300);
  await p.screenshot({ path: out + 'n_settings.png' });
  await p.keyboard.press('Escape');
  step('handbok: räknare, OSI, ordlista, sök');
  await p.evaluate(() => NV.game.ui.handbook('calc')); await p.waitForTimeout(200);
  await p.fill('#calc-in', '10.0.0.2/30'); await p.waitForTimeout(100);
  console.log('   ' + (await p.evaluate(() => document.getElementById('calc-out').innerText)).replace(/\n/g, ' | ').slice(0, 200));
  await p.screenshot({ path: out + 'n_calc.png' });
  await p.evaluate(() => NV.game.ui.handbook('osi')); await p.waitForTimeout(100);
  await p.evaluate(() => NV.game.ui.handbook('fel')); await p.fill('#hb-search', 'duplex'); await p.waitForTimeout(100);
  console.log('   synliga rader vid sök "duplex":', await p.evaluate(() => [...document.querySelectorAll('.tab-body tr')].filter(t => t.style.display !== 'none').length));
  await p.keyboard.press('Escape');
  step('anteckningar, notiser, hjälp, ärenden');
  await p.evaluate(() => NV.game.ui.notesDialog()); await p.waitForTimeout(100); await p.fill('#notes', 'Test'); await p.keyboard.press('Escape');
  await p.evaluate(() => NV.game.ui.logDialog()); await p.waitForTimeout(100); await p.keyboard.press('Escape');
  await p.evaluate(() => NV.game.ui.helpDialog()); await p.waitForTimeout(100); await p.keyboard.press('Escape');
  step('lös fel 2 och skriv rapport med återkoppling');
  await p.evaluate(() => { const s = new NV.IosSession(NV.game.state, 'SW1', { privileged: true }); ['conf t', 'int gi0/5', 'no shut', 'end'].forEach(c => s.handle(c)); NV.sim.refresh(NV.game.state); });
  await p.waitForTimeout(3500);
  console.log('   status:', await p.evaluate(() => JSON.stringify(NV.game.taskState.v1k2)));
  await p.evaluate(() => NV.game.ui.reportPicker()); await p.waitForTimeout(300);
  await p.click('input[name=cause][value="0"]'); await p.click('input[name=fix][value="2"]');
  await p.click('#dialog button.primary'); await p.waitForTimeout(400);
  await p.screenshot({ path: out + 'n_feedback.png' });
  await p.keyboard.press('Escape');
  await p.evaluate(() => NV.game.ui.taskOverview()); await p.waitForTimeout(200);
  await p.click('[data-rep]'); await p.waitForTimeout(200); await p.keyboard.press('Escape');
  step('autosparning och fortsätt');
  await p.evaluate(() => NV.game.saveRun());
  const saved = await p.evaluate(() => !!NV.game.savedRun());
  console.log('   sparad:', saved);
  step('byt till 2D mitt i veckan');
  await p.evaluate(() => NV.game.setMode('2d')); await p.waitForTimeout(1000);
  await p.screenshot({ path: out + 'n_switch2d.png' });
  await p.evaluate(() => NV.game.onInteract({ type: 'rack', id: 'A' })); await p.waitForTimeout(400); await p.keyboard.press('Escape');
  await p.keyboard.press('Escape'); await p.waitForTimeout(200);
  console.log('   paus i 2D:', await p.evaluate(() => !document.getElementById('pause').classList.contains('hidden')));
  await p.click('[data-pause="resume"]');
  step('meny, examen');
  await p.evaluate(() => NV.game.ui.showMenu()); await p.waitForTimeout(300);
  await p.screenshot({ path: out + 'n_menu.png' });
  await p.click('[data-exam]'); await p.waitForTimeout(400);
  if (await p.$('#dialog:not(.hidden)')) { const t = await p.textContent('#dialog .dlg-title'); console.log('   dialog:', t); await p.click('#dialog button.primary'); await p.waitForTimeout(400); }
  if (await p.$('#dialog:not(.hidden)')) await p.click('#dialog button.primary');
  console.log('   examen:', await p.evaluate(() => NV.game.exam + ' vecka ' + NV.game.week));
  await p.evaluate(() => NV.game.ui.hintPicker()); await p.waitForTimeout(100);
  step('ladda om och fortsätt');
  await p.reload(); await p.waitForTimeout(2500);
  const cont = await p.$('[data-continue]');
  console.log('   fortsätt-knapp:', !!cont, 'läge efter omladdning:', await p.evaluate(() => NV.game.mode));
  if (cont) { await cont.click(); await p.waitForTimeout(800); console.log('   fortsatte vecka', await p.evaluate(() => NV.game.week)); }
  console.log(errs.join('\n') || 'inga fel');
  await b.close();
})();
