/** Sample builds for the balance simulator (npm run sim). */
import type { Build } from './sim';

const skill = (id: string, rank = 1) => ({ [`n.${id}`]: rank });

export const BUILDS: Build[] = [
  {
    name: 'L1 starter (Hydraulic Strike)',
    level: 1,
    nodes: {},
    rotation: [{ skill: 'bastion.hydraulic_strike' }],
  },
  {
    name: 'L5 Strike + Seismic Shock',
    level: 5,
    nodes: { ...skill('hydraulic_strike', 2), ...skill('seismic_shock') },
    rotation: [{ skill: 'bastion.seismic_shock' }, { skill: 'bastion.hydraulic_strike' }],
  },
  {
    name: 'L15 Jab + Furnace Cleave (wildfire)',
    level: 15,
    nodes: {
      ...skill('piston_jab', 3),
      'e.piston_jab': 1,
      'm.piston_jab.rapid': 1,
      ...skill('furnace_cleave', 5),
      'e.furnace_cleave': 1,
      'm.furnace_cleave.wildfire': 1,
      'p.hydraulic_power': 3,
    },
    rotation: [{ skill: 'bastion.furnace_cleave' }, { skill: 'bastion.piston_jab' }],
  },
  {
    name: 'L15 Strike + Shock (crushing, rupture)',
    level: 15,
    nodes: {
      ...skill('hydraulic_strike', 3),
      'e.hydraulic_strike': 1,
      'm.hydraulic_strike.crushing': 1,
      ...skill('seismic_shock', 5),
      'e.seismic_shock': 1,
      'm.seismic_shock.rupture': 1,
      'p.hydraulic_power': 3,
    },
    rotation: [{ skill: 'bastion.seismic_shock' }, { skill: 'bastion.hydraulic_strike' }],
  },
  {
    name: 'L30 Reactor Core vent build',
    level: 30,
    nodes: {
      ...skill('hydraulic_strike', 5),
      'e.hydraulic_strike': 1,
      'm.hydraulic_strike.searing': 1,
      ...skill('seismic_shock', 5),
      'e.seismic_shock': 1,
      'm.seismic_shock.rupture': 1,
      ...skill('energy_shield'),
      ...skill('magnetic_pull'),
      ...skill('heat_vent', 5),
      'e.heat_vent': 1,
      'm.heat_vent.controlled': 1,
      ...skill('orbital_strike'),
      'p.hydraulic_power': 3,
      'p.crushing_force': 3,
      'k.reactor_core': 1,
    },
    rotation: [
      { skill: 'bastion.orbital_strike' },
      { skill: 'bastion.heat_vent', minHeat: 90 },
      { skill: 'bastion.seismic_shock', minHeat: 75 },
      { skill: 'bastion.magnetic_pull' },
      { skill: 'bastion.hydraulic_strike' },
      { skill: 'bastion.energy_shield' },
    ],
  },
  {
    name: 'L30 Shockwave Engine + Fist of Kharos',
    level: 30,
    nodes: {
      ...skill('hydraulic_strike', 5),
      'e.hydraulic_strike': 1,
      'm.hydraulic_strike.crushing': 1,
      ...skill('seismic_shock', 5),
      'e.seismic_shock': 1,
      'm.seismic_shock.rupture': 1,
      ...skill('energy_shield'),
      ...skill('magnetic_pull'),
      'e.magnetic_pull': 1,
      'm.magnetic_pull.polarity': 1,
      ...skill('heat_vent'),
      ...skill('orbital_strike'),
      'p.hydraulic_power': 3,
      'p.crushing_force': 3,
      'k.shockwave_engine': 1,
    },
    uniques: ['fist_of_kharos'],
    aspects: [['amulet', 'vulnerability_matrix', 0.18]],
    rotation: [
      { skill: 'bastion.orbital_strike' },
      { skill: 'bastion.magnetic_pull' },
      { skill: 'bastion.seismic_shock' },
      { skill: 'bastion.heat_vent', minHeat: 90 },
      { skill: 'bastion.hydraulic_strike' },
      { skill: 'bastion.energy_shield' },
    ],
  },
  {
    name: 'L30 Heart of Lumen (mythic, no overheat)',
    level: 30,
    nodes: {
      ...skill('hydraulic_strike', 5),
      'e.hydraulic_strike': 1,
      'm.hydraulic_strike.searing': 1,
      ...skill('furnace_cleave', 5),
      'e.furnace_cleave': 1,
      'm.furnace_cleave.wildfire': 1,
      ...skill('energy_shield'),
      ...skill('magnetic_pull'),
      ...skill('heat_vent'),
      ...skill('orbital_strike'),
      'p.hydraulic_power': 3,
      'p.thermal_capacitor': 3,
      'k.reactor_core': 1,
    },
    uniques: ['heart_of_lumen'],
    rotation: [
      { skill: 'bastion.orbital_strike' },
      { skill: 'bastion.furnace_cleave', minHeat: 90 },
      { skill: 'bastion.magnetic_pull' },
      { skill: 'bastion.hydraulic_strike' },
      { skill: 'bastion.energy_shield' },
      { skill: 'bastion.heat_vent', minHeat: 101 },
    ],
  },
];
